In [1]:
import pandas as pd

In [2]:
d=pd.read_csv("titanic.csv")

In [3]:
d

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [4]:
d.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [5]:
d.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [6]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB

In [7]:
d.columns[d.isna().any()]

Index(['age', 'embarked', 'deck', 'embark_town'], dtype='object')

In [8]:
d['embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [9]:
d['embarked']=d['embarked'].fillna(d['embarked'].mode()[0])
d.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [10]:
m=(d["sex"]=="female")&(d["survived"]==1)
m

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888    False
889    False
890    False
Length: 891, dtype: bool

In [11]:
e=pd.get_dummies(d["embarked"])
e

         C      Q      S
0    False  False   True
1     True  False  False
2    False  False   True
3    False  False   True
4    False  False   True
..     ...    ...    ...
886  False  False   True
887  False  False   True
888  False  False   True
889   True  False  False
890  False   True  False

[891 rows x 3 columns]

In [12]:
d.groupby("sex")["survived"].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [13]:
d.groupby("pclass")["survived"].mean()

pclass
1    0.629630
2    0.472826
3    0.242363
Name: survived, dtype: float64

In [14]:
d['age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [15]:
d['age']=d['age'].fillna(d["age"].mean())
d['age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: age, Length: 891, dtype: float64

In [16]:
d.columns[d.isna().any()]

Index(['deck', 'embark_town'], dtype='object')

In [17]:
d.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.002015    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   29.699118    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [18]:
s=pd.get_dummies(d['sex'])
d=pd.concat([d,s],axis=1)
d=d.drop("sex",axis="columns")
d

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,female,male
0,0,3,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,False,True
1,1,1,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,True,False
2,1,3,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,True,False
3,1,1,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,True,False
4,0,3,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,False,True
887,1,1,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,True,False
888,0,3,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,True,False
889,1,1,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,False,True
890,0,3,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,False,True

In [19]:
d.head(10)

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,female,male
0,0,3,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,False,True
1,1,1,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,True,False
2,1,3,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,True,False
3,1,1,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,True,False
4,0,3,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,False,True
5,0,3,29.699118,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True,False,True
6,0,1,54.000000,0,0,51.8625,S,First,man,True,E,Southampton,no,True,False,True
7,0,3,2.000000,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False,False,True
8,1,3,27.000000,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False,True,False
9,1,2,14.000000,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False,True,False

In [20]:
d.tail()

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,female,male
886,0,2,27.000000,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True,False,True
887,1,1,19.000000,0,0,30.00,S,First,woman,False,B,Southampton,yes,True,True,False
888,0,3,29.699118,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False,True,False
889,1,1,26.000000,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True,False,True
890,0,3,32.000000,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True,False,True

In [21]:
de={"name":["nisha","lisa","bosha","vijay","hussain","pradheepa","gavaskar","thaniyarasu","lokesh","anusha"],
"course":["DS","AI","AI","DS","DS","DS","AI","DA","DS","ML"]}
de

{'name': ['nisha',
  'lisa',
  'bosha',
  'vijay',
  'hussain',
  'pradheepa',
  'gavaskar',
  'thaniyarasu',
  'lokesh',
  'anusha'],
 'course': ['DS', 'AI', 'AI', 'DS', 'DS', 'DS', 'AI', 'DA', 'DS', 'ML']}

In [26]:
df=pd.DataFrame(de)
df

          name course
0        nisha     DS
1         lisa     AI
2        bosha     AI
3        vijay     DS
4      hussain     DS
5    pradheepa     DS
6     gavaskar     AI
7  thaniyarasu     DA
8       lokesh     DS
9       anusha     ML

In [30]:
d[(d['survived']>25)&(d["fare"]>50)]

Empty DataFrame
Columns: [survived, pclass, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone, female, male]
Index: []

In [31]:
d.sort_values("fare")

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,female,male
271,1,3,25.000000,0,0,0.0000,S,Third,man,True,NaN,Southampton,yes,True,False,True
597,0,3,49.000000,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True,False,True
302,0,3,19.000000,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True,False,True
633,0,1,29.699118,0,0,0.0000,S,First,man,True,NaN,Southampton,no,True,False,True
277,0,2,29.699118,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,0,1,64.000000,1,4,263.0000,S,First,man,True,C,Southampton,no,False,False,True
341,1,1,24.000000,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False,True,False
737,1,1,35.000000,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True,False,True
258,1,1,35.000000,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True,True,False
679,1,1,36.000000,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False,False,True

In [33]:
d.sort_values("fare",ascending=False)

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,female,male
258,1,1,35.000000,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True,True,False
737,1,1,35.000000,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True,False,True
679,1,1,36.000000,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False,False,True
88,1,1,23.000000,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False,True,False
27,0,1,19.000000,3,2,263.0000,S,First,man,True,C,Southampton,no,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
633,0,1,29.699118,0,0,0.0000,S,First,man,True,NaN,Southampton,no,True,False,True
413,0,2,29.699118,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True,False,True
822,0,1,38.000000,0,0,0.0000,S,First,man,True,NaN,Southampton,no,True,False,True
732,0,2,29.699118,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True,False,True
674,0,2,29.699118,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True,False,True

In [34]:
d['survived'].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [37]:
d['survived'].value_counts(normalize=True)

survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [38]:
d[d['female']& d["survived"]]

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,female,male
1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,True,False
2,1,3,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,True,False
3,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,True,False
8,1,3,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False,True,False
9,1,2,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,1,2,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False,True,False
875,1,3,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True,True,False
879,1,1,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False,True,False
880,1,2,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False,True,False
887,1,1,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,True,False